version: '3.1'

services:
  db:
    image: postgres:alpine3.14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: chayanin3343@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
